---

- name: Installing requirements
  become: yes
  apt: 
    name: "{{ eclipse_req_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: Installing eclipse classic
  become: yes
  shell: sudo snap install eclipse --classic 